data:
    modality: "2D"
    dataset: "CIFAR10"
    image_size: 32
    channels: 3
    random_flip: true
    num_workers: 4
    num_classes: 10

model:
    model_type: "ddpm"
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 2, 2, 2]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.1
    resamp_with_conv: True
    metric: sqeuclidean
    ckpt_dir: "./outs/hdm_cifar10/logs/ckpt.pth"

diffusion:
    beta_schedule: "cosine" 
    num_diffusion_timesteps: 1000
    index: 0
    sig: 1

training:
    batch_size: 256
    n_epochs: 100000
    n_iters: 5000000
    ckpt_store: 25000
    validation_freq: 2000

sampling:
    batch_size: 4
    clamp_threshold: 500
    num_sample: 50000

ihdm:
    K: 200
    blur_sigma_min: 0.5
    blur_sigma_max: 24
    
optim:
    lr: 0.0001
    grad_clip: 1.0
